"""add password_hash to employees

Revision ID: 503561ee6849
Revises: 20260527_0003
Create Date: 2026-05-27 16:03:37.595174

Note: при merge с ai-rag веткой 20260527_0003 был занят ai_rag_tables — поэтому
эта миграция привязана к нему как родительскому.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '503561ee6849'
down_revision: str | None = '20260527_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
